apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: souvik
  title: Example Node.js Template
  description: A template
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Provide details
      required:
        - name
        - email
        - comments
      properties:
        name:
          title: Component Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
        email:
          title: User Email
          type: string
          format: email
          description: Your email for tracking
        comments:
          title: Commit Message
          type: string
          description: Message to use in the Git commit

  steps:
    - id: fetch-base
      name: Fetch Template Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          email: ${{ parameters.email }}

    - id: publish-to-github
      name: Publish to GitHub
      action: github:repo:push
      input:
        repoUrl: github.com?owner=Souvik4002&repo=Basic-Programme
        defaultBranch: main
        sourcePath: "."
        gitCommitMessage: ${{ parameters.comments }}
        force: true

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-to-github'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: View Repository
        url: ${{ steps['publish-to-github'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
