apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: souvik
  title: Example Node.js Template
  description: A template
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Provide details
      required:
        - name
        - email
      properties:
        name:
          title: Component Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
        email:
          title: User Email
          type: string
          format: email
          description: Your email for tracking

  steps:
    - id: fetch-base
      name: Fetch Template Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          email: ${{ parameters.email }}

    - id: push-to-repo
      name: Push directly to existing repo
      action:  github:repo:push
      input:
        repoUrl: github.com?owner=Souvik4002&repo=Basic-Programme
        branch: main
        targetPath: '.'
        message: "Pushed by Backstage template for ${{ parameters.email }}"
        author:
          name: Backstage Bot
          email: backstage@example.com
        overwrite: true

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['push-to-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: View Repository
        url: ${{ steps['push-to-repo'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
